<?php
// 001
// If we list all the natural numbers below 10 that are multiples of 3 or 5, 
// we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.

// $array = [];
// for ($i = 1; $i < 1000; $i++) {
//     if ($i % 3 == 0 || $i % 5 == 0){
//         array_push($array, $i);    
//     }
// }
// echo array_sum($array) . PHP_EOL;



// 002
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not 
// exceed four million, find the sum of the even-valued terms.

// $sum = 0;
// $array = [1,2];
// $n = 1;
// do {
//     array_push($array, ($array[$n-1] + $array[$n]));
//     $n++;
// } while (end($array) < 4000000);

// foreach ($array as $number) {
//     if ($number % 2 ==0){
//         $sum += $number;
//     }
// }
// echo $sum . PHP_EOL;



// 003
// The prime factors of 13195 are 5, 7, 13 and 29.
// What is the largest prime factor of the number 600851475143 ?



?>